- hosts: tomcat,docker
  tasks:
    - name: Installs apache web server
      apt: pkg=apache2 state=installed update_cache=true

    - name: Push future default virtual host configuration
      copy: src=files/awesome-app.conf dest=/etc/apache2/sites-available/ mode=0640

    - name: Activates our virtualhost
      command: a2ensite awesome-app

    - name: Check that our config is valid
      command: apache2ctl configtest

    - name: Deactivates the default virtualhost
      command: a2dissite 000-default.conf

    - name: Deactivates the default ssl virtualhost
      command: a2dissite default-ssl.conf
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
