- hosts: tomcat
  tasks:
    - name: Installs apache web server
      apt: pkg=apache2 state=installed update_cache=true

    - name: Push future default virtual host configuration
      copy: src=files/awesome-app.conf dest=/etc/apache2/sites-available/ mode=0640

    - name: Activates our virtualhost
      command: a2ensite awesome-app

    - name: Check that our config is valid
      command: apache2ctl configtest
      register: result
      ignore_errors: True

    - name: Rolling back - Restoring old default virtualhost
      command: a2ensite 000-default.conf
      when: result|failed

    - name: Rolling back - Removing our virtualhost
      command: a2dissite awesome-app.conf
      when: result|failed

    - name: Rolling back - Ending playbook
      fail: msg="Configuration file is not valid. Please check that before re-running the playbook."
      when: result|failed

    - name: Deactivates the default virtualhost
      command: a2dissite 000-default.conf

    - name: Deactivates the default ssl virtualhost
      command: a2dissite default-ssl.conf
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
